### ISSUE TITLE
Додати логування

### ISSUE THREAD

**Issue by das13** [aleks-vorgen/NCTaskManager#11]
Додати в проект логгер згідно з вимогами п.6
Після додавання логгера потрібно замінити всі e.printStackTrace() (принаймні у catch блоках) на виклик логгера.
Логгер повинен мати конфігурацію, відмінну від конфігурації за замовчуванням.

**Comment by aleks-vorgen** [comment]
Додав логування
Коміт: 64347d6beef059c1d86291c972c8284c9d0acb09
