### ISSUE TITLE
Додати нотифікацію

### ISSUE THREAD

**Issue by das13** [aleks-vorgen/NCTaskManager#12]
Згідно з вимогами (п.4) додатоток має сповіщати користувача в момент, коли деяка задача має бути виконана.
Потрібно добавити таке сповіщення.
Сповіщення можна реалізувати за допомогою додаткового потока-демона

**Comment by aleks-vorgen** [comment]
Додав нотифікацію
Коміт: e96ffdb8d3fe9fba6a9901c5d5510e9d546e93c8
