### ISSUE TITLE
Винести строкові константи

### ISSUE THREAD

**Issue by das13** [aleks-vorgen/NCTaskManager#13]
Винести строкові константи, що повторюються, наприклад в IOController res, res/bin, /binary.bin та ін. в батьківський клас (наприклад, або в окреми клас)
Див. #14

**Comment by aleks-vorgen** [comment]
Строкові константи в IOController винесені як статичні атрибути класу.
Коміт: 4e0e5b411dcc21b1b471dc3612398a7a98bcce46
