### ISSUE TITLE
[REFACTOR] Змінити поведінку MVC

### ISSUE THREAD

**Issue by das13** [aleks-vorgen/NCTaskManager#17]
В петерні MVC всим керує контролер. В даному проекті - View.
Таку поведінку бажано змінити т.ч., щоб контролер давав команди View на відображення, а View займалося лише відображенням.

**Comment by aleks-vorgen** [comment]
Змінена поведінка MVC
Також виконано Issue #15 
Коміт: 705647ecf5726a617a739ebb96d85b3ade03e98a
