### ISSUE TITLE
Нотифікація потребує доопрацювання

### ISSUE THREAD

**Issue by das13** [aleks-vorgen/NCTaskManager#18]
![изображение](https://user-images.githubusercontent.com/10417869/180600141-2827cbfc-736e-421a-af39-cf81a78ff94c.png)
Не корректно відображається сповіщення

**Comment by aleks-vorgen** [comment]
Додав "timestamp" до сповіщень
Коміт: 5b114c3eb14d3eb8a663e07de857a65849f13811
