### ISSUE TITLE
Відловлювання NPE

### ISSUE THREAD

**Issue by das13** [aleks-vorgen/NCTaskManager#21]
В **ua.edu.sumdu.j2se.kulykov.tasks.views.Notificator.run**
`catch (NullPointerException e)`
Це не зовсім вірно. Краще перевіряти на нерівніст null.

**Comment by aleks-vorgen** [comment]
Змінено catch блок на перевірку if
Коміт: f9c50ed3f5ffd15daffd910e4a2d41afc1595649
