### ISSUE TITLE
Обов'язково закривати ресурси

### ISSUE THREAD

**Issue by das13** [aleks-vorgen/NCTaskManager#22]
В методах
ua.edu.sumdu.j2se.kulykov.tasks.views.AddEditRemoveView#getDateTimeInput
ua.edu.sumdu.j2se.kulykov.tasks.views.AddEditRemoveView#getIntervalInput
ua.edu.sumdu.j2se.kulykov.tasks.views.ShowTasksView#getDateInput
ua.edu.sumdu.j2se.kulykov.tasks.views.View#getYesNoInput
не закривається ресурс **Scanner**
Після використання такі ресурси потрібно закривати - за допомогою **try with resources** або **finally**
Також можна використати один Scanner на весь додаток.

**Comment by aleks-vorgen** [comment]
Використовується лише 1 екземпляр сканеру. Ресурс закривається при завершенні програми
Додав метод, що виводить повідомлення з новим рядком
Коміт: b0e503e553b8ba33c962f432c08f047ea3629456
