### ISSUE TITLE
Винести в константи

### ISSUE THREAD

**Issue by das13** [aleks-vorgen/NCTaskManager#23]
Винести в константи вирази в **case** у:
ua.edu.sumdu.j2se.kulykov.tasks.controllers.TaskController#showMenu
ua.edu.sumdu.j2se.kulykov.tasks.views.ShowTasksView#menu (також і значення, що повертаються у **return**)
ua.edu.sumdu.j2se.kulykov.tasks.views.IOView#menu
ua.edu.sumdu.j2se.kulykov.tasks.controllers.IOController#showMenu
ua.edu.sumdu.j2se.kulykov.tasks.views.AddEditRemoveView#menu

у ua.edu.sumdu.j2se.kulykov.tasks.views.Notificator#run - `LocalDateTime.now().plusMinutes(5);` 5 - константа (можна і 30000)

**Comment by das13** [comment]
Додатково:
switch/case вигляду
```
case "1":
    return 1;
case "2":
    return 2;
case "3":
    return 3;
case "4":
    return 4;
case "5":
    return 5;
case "6":
    return 6;
case "7":
    return 7;
```
зручно буде замінити на перетворення цифрового String на число

**Comment by aleks-vorgen** [comment]
Винесені константи та рефакторинг методів menu() та showMenu()
Коміт: a976ec1f3d9cbffb01fc83403fe5b7fb04c5e248
