### ISSUE TITLE
Виправити catch

### ISSUE THREAD

**Issue by das13** [aleks-vorgen/NCTaskManager#25]
```
try {
    tmp = Integer.parseInt(choice);
    if (tmp < 1 || tmp > 3)
        throw new IllegalArgumentException("This option does not exists");
    return tmp;
} catch (NumberFormatException e) {
    LOG.info("User entered impossible to parse to int input (" + choice + ")");
    messageln("Invalid input");
    message("Type your choice: ");
    choice = SCANNER.nextLine();
} catch (IllegalArgumentException e) {
    LOG.info("User entered nonexistent point (" + tmp + ")");
    messageln(e.getMessage());
    message("Type your choice: ");
    choice = SCANNER.nextLine();
}
```
Так робити не можна. Введені дані потрібно перевіряти в IF.
Наприклад, якщо в секції catch теж буде введено неправильний символ, то обробить помилку т.ч. вже буде неможливо.

**Comment by aleks-vorgen** [comment]
Закрываючи сканер, в який передано System.in, закривається потік, тому повторно не вийде скористуватися сканером.
https://ru.stackoverflow.com/questions/721901/После-scanner-close-как-работать-со-scanner

З треду: "Сам Scanner не является ресурсом, требующим освобождения, таковым является InputStream переданный в него. Если вы передаете System.in, то закрывать его не нужно".

Коміт: 126d43e71424c6495997db8158725f1054444509
